src/backup.c

Here's a patch trying to fix the issue #20.

Skip system_identifier check on PostgreSQL 9.5

---

src/backup.c
src/dir.c

Skip copying of non-data files during incremental backup if they have not changed since last backup.

Skip unchanged files

---

src/backup.c
src/catalog.c
src/delete.c
src/help.c
src/merge.c
src/pg_probackup.c
src/pg_probackup.h
src/restore.c
src/validate.c
tests/expected/option_help.out

Requested by: https://github.com/postgrespro/pg_probackup/issues/52
Allow "backup" command to use --no-validate flag, also allow DONE backup to be a parent of incremental backup.
Now restore of incremental chain of DONE backups looks like this:
https://pastebin.postgrespro.ru/?2ffdacdefe553900#TZo3xpf6RV+jWq97Ye5Kikxtuw0c033rQsU45jwMFt8=
Probably we should be more lenient to DONE backups and try to validate them before restore.
Should be DONE backups to be allowed to be restored without validation ?

Issue 52: --no-validate flag for backup

---

src/backup.c
src/data.c
src/merge.c
src/pg_probackup.h
src/restore.c

copy_file and backup_data_file() always treat missing source file as non-error condition.
Added missing_ok flag to remedy that.

Issue 74: copy_file and backup_data_file() lax behavior 

---

src/help.c
src/pg_probackup.c
src/pg_probackup.h
src/utils/configuration.c
src/utils/configuration.h
src/utils/file.c

Избавился от одной глобальной переменной, переписал бесконечные "else if (strcmp(..."

remove backup_subcmd global variable and useless command_name variable

---

tests/archive.py
tests/backup.py
tests/compatibility.py
tests/delta.py
tests/exclude.py
tests/external.py
tests/helpers/ptrack_helpers.py
tests/incr_restore.py
tests/merge.py
tests/page.py
tests/ptrack.py
tests/replica.py
tests/restore.py
tests/retention.py
tests/show.py
tests/time_stamp.py

With autovacuum enabled tests are unstable. Especially they are unstable
if postgresql is running under valgrind and therefore is severely
inhibited (and vacuum has time to be triggered).

tests: disable autovacuum by default

---

src/data.c
src/restore.c
src/util.c
src/utils/pgut.c
src/utils/pgut.h

valgrind detected some uninitialized memory usage.
Looks like shift_lsn one is a real bug.

Fix some valgrind alerts

---

src/backup.c
src/checkdb.c
src/ptrack.c
src/util.c
src/utils/pgut.c
tests/CVE_2018_1058.py
tests/__init__.py

CVE-2018-1058 fixes

---

tests/backup.py
tests/replica.py

See https://www.postgresql.org/message-id/flat/20210901.121225.1339494423357751537.horikyota.ntt%40gmail.com#ba576416b65f28725488861280805e84
So we can revert two workarounds:
* Revert "[PGPRO-5378] fix unstable tests.replica.ReplicaTest.test_replica_archive_page_backup"
This reverts commit 90b9b5745e19909a6f5f28761def49ef6bfef0e4.
* Revert ""fix" unstable backup.BackupTest.test_backup_with_less_privileges_role (disable tests in archive mode from replica)"
This reverts commit 5dcd1ce2b817219180005b1b70a231798cd96ec5.

[PGPRO-5387] Vanilla fixed idle replica archiving

---

packaging/pkg/scripts/rpm.sh
packaging/test/scripts/rpm.sh
packaging/test/scripts/rpm_forks.sh
src/data.c
src/delete.c

Fix comparison unsigned expression

---

tests/exclude.py

UNLOGGED table should be restored as empty with `"select count(*) from table" == 0`. such kind of test is added 
https://github.com/postgrespro/pg_probackup/issues/360

PBCKP-145: added check of unlogged table is restored as empty table

---

src/utils/file.c
src/utils/remote.c

ControlMaster=yes or ControlMaster=auto in ~/.ssh/config could lead to ssh client stall. Override this setting.
Also, make fast agent exit on FIO_DISCONNECT .
And close fio_stderr in fio_disconnect.

rapid agent close + disable ssh control master.

---

tests/helpers/ptrack_helpers.py
tests/option.py

For correct work test_help_6 we need skip this test if PostgreSQL configured without --enable-nls

Add checking enable-nls option in configure 

---

src/pg_probackup.h
src/utils/file.c
src/utils/file.h
src/utils/remote.c
tests/compatibility.py

REL_2_5-PBCKP-236

---

.travis.yml
README.md

[PBCKP-235] README.md now contains correct package versions

---

src/archive.c
src/catalog.c
src/data.c
src/dir.c
src/merge.c
src/pg_probackup.h
src/utils/file.c
src/utils/file.h
tests/cfs_backup.py
tests/cfs_catchup.py
tests/expected/option_version.out
tests/helpers/ptrack_helpers.py

- store cfm files truncated to non-zero head with coarse granularity (64-4096 bytes)
- and calculate crc for truncated file
- during restoration calculate crc for cfm as if it was truncated

[PBCKP-146] truncate cfm files

---

tests/helpers/ptrack_helpers.py

This modification allows one to set PGPROBACKUPBIN to a binary included in PATH.

Respect PATH in a  pg_probackup binary check

---

src/dir.c
tests/backup.py
tests/ptrack.py

It were lost during fork-name detection fix at eaf3b14c22 . And since there were no basic test for this, it were not detected.

Fix segno calculation.

---

src/archive.c
src/backup.c
src/catalog.c
src/catchup.c
src/checkdb.c
src/data.c
src/delete.c
src/dir.c
src/fetch.c
src/merge.c
src/pg_probackup.c
src/pg_probackup.h
src/restore.c
src/show.c
src/util.c
src/utils/file.c
src/utils/file.h
src/validate.c

- don't use full `struct stat` since it differs between platforms
- store file kind separately from mode in pb specific way
- add pioFilesAreSame as replacement of fio_is_same_file since it needs st_ino and st_dev, therefore had to run on localdrive always.

rework file stat handling to simplify and cross-platform-ability

---

src/parsexlog.c

Pg15 now reports if it didn't met expected contrecord. Absence of this message was long standing bug in previous postgres versions.
This situation could happen if WAL segment was rewritten after restart.
It causes "tests.validate.ValidateTest.test_validate_wal_unreal_values" to hang but (looks like) for other reason: test tries to read "in future".
Probably we should stop reading logs here. But since we always did continue here, lets continue as well.

[PBCKP-354] Pg15: continue reading if error "missing contrecord" is met.

---

src/catalog.c

pg_multixact contains files which looks like db files, but they are not.
get_backup_filelist should not pass to set_forkname files not in db folder nor `global` folder.
Fixes #585

Fix warning in get_backup_filelist
